version: "3.8"
services:
  base: &base
    image: notification_base:v0.1
    build:
      context: .
    network_mode: host
    tmpfs:
      - /tmp

  backend: &backend
    <<: *base
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: "/app"
    env_file:
      - ".env"
  api:
    <<: *backend
    pid: host
    command: bundle exec rails s -p 4040 -b '0.0.0.0'
    ports:
      - "4040:4040"
  sidekiq:
    <<: *backend
    pid: host
    command: bundle exec sidekiq -c 1
